version: '3'
services:
  helloworld:
    image: geekcu/helloworld
  mynginx:
    image: geekcu/mynginx:JR10
    ports:
    - "5001:80"
  mycat:
    image: geekcu/cat:JR10
    ports:
    - "5000:5000"
